# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
  - covr

matrix:
  include:
  - r: 3.5
  - r: 3.6
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
